environment: "prod"
name_prefix: ""
name_postfix: ""
domain: "drift.com"
internal_domain: "int.drift.com"
aws_region: "us-east-1"
availability_zones: ["us-east-1a", "us-east-1c"]
vpc_cidr: "10.20.0.0/16"
public_subnet_cidrs: ["10.20.32.0/20", "10.20.96.0/20"]
private_subnet_cidrs: ["10.20.0.0/19", "10.20.64.0/19"]
vpn_client_cidr: "192.168.255.0/24"
app_name: drift-translator