environment: "#{atmos_env}"
name_prefix: ""
name_postfix: "-qa"
domain: "driftqa.com"
internal_domain: "int.driftqa.com"
aws_region: "us-east-1"
availability_zones: ["us-east-1a", "us-east-1c"]
vpc_cidr: "10.10.0.0/16"
public_subnet_cidrs: ["10.10.32.0/20", "10.10.96.0/20"]
private_subnet_cidrs: ["10.10.0.0/19", "10.10.64.0/19"]
vpn_client_cidr: "192.168.255.0/24"
app_name: drift-translator