# Provider specific overrides for the aws provider
#
# You can add overrides for other providers by creating a <provider>.yml file in
# this directory where <provider> is the provider name.
#
# Overrides in this file should NOT be scoped under a "providers ->
# <provider>" hash like they need to be in atmos.yml
#
auth:
  session_duration: 3600
  assume_role_name: "ops-admin"
  bootstrap_assume_role_name: "ops-admin"
backend:
  type: s3
  bucket: "drift-ops-terraform"
  key: "pse-drifttranslator/#{atmos_env}/terraform.tfstate"
  region: us-east-1
  encrypt: true
secret:
  type: s3
  bucket: "drift-ops-terraform-secrets"
  prefix: "pse-drifttranslator/#{atmos_env}/"
  region: us-east-1
  encrypt: true
